name: icaro_app
description: Application to track and display Icaro's project data (see https://github.com/LaboratorioGluon/Icaro)

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # graphic:
  #   path: ./
  intl: ^0.17.0
  quiver: ^3.0.1+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/