; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = espidf
board_build.partitions = partitions_custom.csv
build_flags = 
    -DBOARD_HAS_PSRAM

lib_deps=
    https://github.com/libwifi/libwifi.git#0.0.10
    https://github.com/mavlink/c_library_v2#cc11c5b


monitor_speed = 115200

[env:esp32-s3-devkitc-1-n16r8v]
board = esp32-s3-devkitc-1-n16r8v


[env:esp32cam]
board = esp32cam

build_flags =
    -DCAM32
