#!/bin/bash

# Read arguments
if [ -z "$1" ]; then
    echo "Usage: $0 <wifi_interface>"
    exit 1
fi
INTERFACE="$1"

# airmon-ng tool adds "mon" at the end of the interface
if [[ "$INTERFACE" == *mon ]]; then
    MON_INTERACE=$INTERFACE
    BASE_INTERFACE="${INTERFACE%mon}"
    echo "Monitor interface: $MON_INTERACE"
    echo "Base interfaz: $BASE_INTERFACE"
else
    BASE_INTERFACE="$INTERFACE"
    echo "Base interface: $BASE_INTERFACE"
fi

# Stop monitor interface generated by airmon-ng
if iw dev | grep -q "${BASE_INTERFACE}mon"; then
    echo "Deactivating monitor mode with airmon-ng..."
    sudo airmon-ng stop ${BASE_INTERFACE}mon
fi

# Restore managed mode for interface
echo "Restoring managed mode for: $BASE_INTERFACE"
sudo ip link set $BASE_INTERFACE down
sudo iw dev $BASE_INTERFACE set type managed
sudo ip link set $BASE_INTERFACE up

# Restart common network services stopped by airmon-ng
echo "Restarting network services"
sudo systemctl restart NetworkManager 2>/dev/null || echo "Could not restart: NetworkManager"
sudo systemctl restart wpa_supplicant 2>/dev/null || echo "Could not restart: wpa_supplicant"

# Print current mode of interface
echo "The $BASE_INTERFACE should be in managed mode."
echo "Please verify before continuing:"
iw dev $BASE_INTERFACE info
